feat: update nacos docker starter.

diff --git a/globals b/globals
--- a/globals
+++ b/globals
@@ -1,6 +1,45 @@
 #!/usr/bin/env bash
 # author: yooonn
 
+function assert_docker_available() {
+  docker -v 1>/dev/null 2>&1 || (echo "Docker not installed" && exit 1)
+
+  docker ps 1>/dev/null 2>&1 || (echo "Docker not started" && exit 1)
+}
+
+# assert_container_not_exist container_name
+function assert_container_not_exist() {
+  assert_docker_available
+
+  docker ps -a | grep "$1" >/dev/null 2>&1 || return 0
+  echo "Container \`$1\` already existed!"
+  exit 1
+}
+
+# assert_container_exist container_name
+function assert_container_exist() {
+  assert_docker_available
+
+  docker ps -a | grep "$1" >/dev/null 2>&1 && return 0
+  echo "Container \`$1\` not exist!"
+  exit 1
+}
+
+function restart_container() {
+  assert_container_exist "$1"
+  docker restart "$1" || exit 1
+}
+
+# create_network_if_absent network_name
+function create_network_if_absent() {
+  assert_docker_available
+
+  #    docker ps -a | grep "$1" || (echo "container $1 not found." && exit 1)
+  docker network ls | grep "$1" 1>/dev/null ||
+    (printf "Network \`%s\` not found. Creating it!\n" "$1" &&
+      docker network create -d bridge "$1" || exit 1)
+}
+
 function find_dir() {
   find_dir0 "$(
     cd "$(dirname "$1")" || exit 1
@@ -35,7 +74,13 @@ find_dir "$0"
 # SH_DIR
 # ROOT_DIR
 # VOLUMES_DIR
-# DOCKER_NETWORK
+# YOO_NETWORK
+# MYSQL_NETWORK
+# MYSQL_ALIAS
+# NACOS_ALIAS
+# MYSQL_USER
+# MYSQL_PASSWD
+# MYSQL_PORT
 
 # shellcheck disable=SC2034
 SH_DIR="$sh_dir"
@@ -44,4 +89,16 @@ ROOT_DIR="$root_dir"
 # shellcheck disable=SC2034
 VOLUMES_DIR="$volumes_dir"
 # shellcheck disable=SC2034
-DOCKER_NETWORK="netyooonn"
+YOO_NETWORK="netyooonn"
+# shellcheck disable=SC2034
+MYSQL_NETWORK="$YOO_NETWORK"
+# shellcheck disable=SC2034
+MYSQL_ALIAS=mysql8
+# shellcheck disable=SC2034
+NACOS_ALIAS=nacos
+# shellcheck disable=SC2034
+MYSQL_USER=root
+# shellcheck disable=SC2034
+MYSQL_PASSWD=root
+# shellcheck disable=SC2034
+MYSQL_PORT=3307
